name = "VKRegistry"
uuid = "76a9c5e0-a7d9-11e8-0892-f17679cfb529"
authors = ["Tim Bradt <tjbradt@mtu.edu>"]
version = "0.1.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"
